version: "3"
services:
  postgres:
    container_name: postgres
    image: postgres:latest
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    env_file:
    - .env
    ports:
    - "${POSTGRES_PORT}:5432"
    volumes:
    - ./data/postgres:/docker-entrypoint-initdb.d
    networks:
    - postgres

  pgadmin:
    links:
    - postgres:postgres
    container_name: pgadmin
    image: dpage/pgadmin4
    env_file:
    - .env
    ports:
    - "${PGADMIN_PORT}:80"
    volumes:
    - /data/pgadmin:/root/.pgadmin
    networks:
    - postgres

networks:
  postgres:
    driver: bridge
