name: CI Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Create .env file for database
        run: touch /home/runner/work/FindYourPet/FindYourPet/src/backend/database/.env

      - name: Create .env file for backend
        run: touch /home/runner/work/FindYourPet/FindYourPet/src/backend/.env

      - name: Set .env file for database
        run: echo "${{secrets.ENV_FILE}}" >> ./src/backend/database/.env

      - name: Set .env file for backend
        run: echo "${{secrets.ENV_FILE}}" >> ./src/backend/.env

      - name: Start containers
        run: docker-compose -f "./src/backend/database/docker-compose.yml" up -d --build

      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
        working-directory: ./src/backend
      - name: Build npm
        run: npm run build --if-present
        working-directory: ./src/backend
      - name: Start tests
        run: npm test
        working-directory: ./src/backend

      - name: Stop containers
        if: always()
        run: docker-compose -f "./src/backend/database/docker-compose.yml" down
