name: CI Backend

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '14.x'
      - name: Install dependencies
        run: npm install
        working-directory: ./src/backend
      - name: Build npm
        run: npm run build --if-present
        working-directory: ./src/backend
      - name: Start tests
        run: npm test
        working-directory: ./src/backend
