# This workflow connect to infra vpn, connect with ssh to WM and execute local script.

name: Findyourpet deployment

on:
  workflow_run:
    workflows: ["CI Backend"]
    branches: [ main ]
    types:
      - completed
    
jobs:
  push_to_registry:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Push Docker and pull on remote
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
      
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build the Docker image frontend
        run: docker build src/frontend --tag ${{ secrets.DOCKER_USERNAME }}/frontendfyp:latest 
      - name: Docker push frontend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/frontendfyp    
      - name: Build te Docker image backend
        run: docker build src/backend --tag ${{ secrets.DOCKER_USERNAME }}/backendfyp:latest 
      - name: Docker push backend
        run: docker push ${{ secrets.DOCKER_USERNAME }}/backendfyp      
      - name: Create SSH file
        run: touch SSH.pem
      - name: Write key
        run: echo "${{secrets.SSH_KEY}}" >> SSH.pem
      - name: Change permission
        run: chmod 400 SSH.pem  
      - name: connect to SSH
        run: sudo ssh -o StrictHostKeyChecking=no ${{secrets.SSH_USER}}@${{secrets.SSH_HOST}} -i "SSH.pem" "./deploy.sh"
   
    
      

    
